# Generated by Django 6.0.7 on 2026-08-04 13:53

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_email',
            field=accounts.fields.EncryptedCharField(blank=True, default=''),
        ),
    ]
