# Generated by Django 6.0.7 on 2026-08-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('invited', 'Invited')], default='active', max_length=10),
        ),
    ]
