# Generated by Django 6.0.7 on 2026-08-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('voice', 'Voice')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
