# Generated by Django 6.0.7 on 2026-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingmodule_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='best_practices',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='category',
            field=models.CharField(choices=[('phishing', 'Phishing'), ('smishing', 'Smishing'), ('vishing', 'Vishing'), ('social_engineering', 'Social Engineering'), ('password_security', 'Password Security'), ('popup_phishing', 'Pop-up Phishing'), ('evil_twin_phishing', 'Evil Twin Phishing')], default='phishing', max_length=30),
        ),
    ]
