# Generated by Django 6.0.7 on 2026-08-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_trainingmodule_pass_mark_userprogress_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='viewed_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='viewed_scenario',
            field=models.BooleanField(default=False),
        ),
    ]
